version: '3'
services:
    server:
        image: sourcegraph/server:2.6.8
        ports:
            - 7080:7080
        networks:
            - lsp
        volumes:
            - opt:/var/opt/sourcegraph
            - etc:/etc/sourcegraph
    typescript:
        image: sourcegraph/codeintel-typescript
        networks:
            - lsp
    python:
        image: sourcegraph/codeintel-python
        networks:
            - lsp
networks:
    lsp:
volumes:
    opt:
    etc:
